VIDEO_STATUS_PENDING = "pending"
VIDEO_STATUS_PROCESSING = "processing"
VIDEO_STATUS_COMPLETED = "completed"
VIDEO_STATUS_FAILED = "failed"

JOB_STATUS_PENDING = "pending"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_COMPLETED = "completed"
JOB_STATUS_FAILED = "failed"

CLIP_EXPORT_STATUS_PENDING = "pending"

PROCESSING_JOB_TYPE_MOCK_PIPELINE = "mock_pipeline"
PROCESSING_JOB_TYPE_EXTRACT_AUDIO = "extract_audio"
